version: '3.8'

# Docker Compose Reference
# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/

services:
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./bat_stats:/app/bat_stats
    ports:
      - 8080:8080
    environment:
      DEBUG: 1
      SECRET_KEY: foo
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: bat_stats
      SQL_USER: django
      SQL_PASSWORD: django
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      POSTGRES_DB: bat_stats

volumes:
  postgres_data:



