# Generated by Django 5.0 on 2023-12-06 01:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('deck_size', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=1000)),
                ('icon', models.CharField(max_length=1000)),
                ('is_team', models.BooleanField(verbose_name='Is Team?')),
                ('eternal', models.BooleanField(verbose_name='Is Eternal?')),
                ('only_allow_affiliation_characters', models.BooleanField()),
                ('only_allow_affiliation_cards', models.BooleanField()),
                ('only_allow_affiliation_keyword_characters', models.BooleanField()),
                ('only_allow_affiliation_keyword_cards', models.BooleanField()),
                ('affiliation_keyword_boss_must_be_leader', models.BooleanField()),
                ('must_select_leader_as_boss', models.BooleanField()),
                ('can_include_characters_with_same_name', models.BooleanField()),
                ('affiliation_trait_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
