# Generated by Django 5.0 on 2023-12-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_editor', '0002_affiliations'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliations',
            name='app_order',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
