# Generated by Django 5.0 on 2023-12-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_editor', '0003_affiliations_app_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliations',
            old_name='affiliation_trait_ids',
            new_name='affiliation_keyword_trait_ids',
        ),
    ]
