# Generated by Django 5.0 on 2023-12-06 03:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_editor', '0004_rename_affiliation_trait_ids_affiliations_affiliation_keyword_trait_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliations',
            name='app_version',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='list_editor.appmodelversion'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=1000)),
                ('objective_type_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('affiliation_id', models.IntegerField(null=True)),
                ('preventing_trait_id', models.IntegerField(null=True)),
                ('trait_id', models.IntegerField(null=True)),
                ('rank_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('required_character_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('app_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_editor.appmodelversion')),
            ],
        ),
    ]
